version: '3.7'
services:

  itwork-bbs365-mysql:
    image: 'mysql:5.7'
    container_name: itwork-bbs365-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - 3306:3306
    volumes:
      - './database-inited/mysql/db/conf.d:/etc/mysql/conf.d'
      - './database-inited/mysql/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'

  itwork-bbs365-server:
    image: mlogclub/itwork-bbs365-server
    container_name: itwork-bbs365-server
    ports:
      - 8082:8082
    depends_on:
      - itwork-bbs365-mysql
    build:
      target: application
      context: server
    restart: on-failure
    volumes:
      - './databases/data:/data/'

  itwork-bbs365-site:
    image: mlogclub/itwork-bbs365-site
    container_name: itwork-bbs365-site
    ports:
      - 3000:3000
    build:
      target: application
      context: site
    depends_on:
      - itwork-bbs365-server
    restart: on-failure
